### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by yzk0281** [pinguo-luhaofang/tripletloss#1]
Hello,
how to use your tripletloss python layer?
I  'make pycaffe' and put the folder 'tripletloss' in /usr/lib/python2.7/dist-packages,
but when I start to train with tripletloss-master/example_layer/model/solver.prototxt,
it says:
Creating layer norm2
ImportError: No module named tripletloss.norm2layer
Could give me some advise please?

**Comment by yzk0281** [comment]
I also tried ：
make distribute
and:
export PYTHONPATH=/root/cnn/caffe-master/distribute/python:$PYTHONPATH
in  ~/.bashrc
source ~/.bashrc

**Comment by pinguo-luhaofang** [comment]
Hi,
You may insert folder path to your PYTHONPATH path.

import sys
sys.path.insert(0,'$ your tripletloss root path $')

**Comment by yzk0281** [comment]
still same problem...I train it via this ：
./build/tools/caffe train -solver python/tripletloss-master/example_layer/model/solver.prototxt -weights examples/vgg_face_caffe/VGG_FACE.caffemodel
is  it  ok?

**Comment by pinguo-luhaofang** [comment]
Please ,try train.py

**Comment by yzk0281** [comment]
ok...

**Comment by yzk0281** [comment]
Did you trained VGGFACE with it? How is the accuracy?

**Comment by pinguo-luhaofang** [comment]
Maybe I'll give you my proposal's result,several days' later~  : )

**Comment by yzk0281** [comment]
cool~
