### ISSUE TITLE
Hi，谢谢你的triplet网络。请问我准备训练一个112*112大小的vggface 先训练softmax分类 再finetune triplet是否需要更改网络结构

### ISSUE THREAD

**Issue by yzk0281** [pinguo-luhaofang/tripletloss#11]
另，请问能否共享下你在997个人上训练softmax分类的solver和网络初始化文件？
请问你的997个人数据均衡吗？每个人有多少张图片
我准备在webface上训练 我做了处理 10张以下的人过滤掉 现在有10010个人  40W张图片
目前的尝试都不收敛。。有没有什么建议？谢谢

**Comment by pinguo-luhaofang** [comment]
你好，vgg的输入数据是224×224的，具体的请参见论文。
