### ISSUE TITLE
Hi 请问你放出来的模型是自己从头开始训练的还是在官方的模型基础上finetune的？

### ISSUE THREAD

**Issue by yzk0281** [pinguo-luhaofang/tripletloss#14]
请问你的数据里面包含官方的vgg数据吗？

**Comment by pinguo-luhaofang** [comment]
你好，目前模型还没有更新，你现在看到的tripletloss模型并不是新代码产出的，pretrained的模型是softmax训练的，并没有达到非常好的收敛，不过已经在下降区域中，你可以通过pretrained的模型进行finetune。
我的dataset是非公开的，有结合一小部分celebface的data
