### ISSUE TITLE
Hi, What have you extract feature?

### ISSUE THREAD

**Issue by peternara** [pinguo-luhaofang/tripletloss#17]
I completed the training.
but i wonder extracted feature name on your deploy.prototxt.
"fc9_1(512)" or fc7(4096) or others ???

thank you.

**Comment by pinguo-luhaofang** [comment]
The output feature should be extracted from "fc9_1".

**Comment by yzk0281** [comment]
Hello, 请问您实现的norm2layer层和caffe自带的Normalize层区别在哪儿?
deploy.prototxt中的倒数第三层norm2layer类型能不能用Normalize代替？

**Comment by peternara** [comment]
@pinguo-luhaofang 
i thank you about answer. :)
 i have one more question.
you write "I trained a 256 dim output model, the results for clustering".

"256 dim" mean fc9_1's dimension????

thank you.

**Comment by yzk0281** [comment]
Hello, what is your "I trained a 256 dim output model, the results for clustering" mean?
fc9_1 is 512 dim I think~
