### ISSUE TITLE
loss居高不下

### ISSUE THREAD

**Issue by zhangfudiyi** [pinguo-luhaofang/tripletloss#18]
你好！我有485个人脸图，每个人80张。我将train.prototxt 以及solver中的参数改了很多次，在softmax训练时loss一直在3到8直接徘徊，这个有木有解决办法！是数据量太少了？还有就是人脸必须先做矫正吗？

**Comment by pinguo-luhaofang** [comment]
需要做人脸的alignment，crop然后作为输入进行训练。
softmax要调整参数训练，如果不收敛，建议你finetune。
还有看看你的test准确率吧。

**Comment by zhangfudiyi** [comment]
我已经微调很多次了，测试精度为0，可能原因是我没有alignment，我将先将图片进行处理一下，谢谢你的建议！ thank you so much ！ @pinguo-luhaofang

**Comment by zhangfudiyi** [comment]
再来感谢一下你 @pinguo-luhaofang ！第一次学卷积神经网络，第一次跑人脸识别程序，终于搞出来了，测试多张图片，结果杠杠的好。虽然我还没有加tripletloss，但是这个softmax已经很强大了！继续学习！谢谢啦！

**Comment by dianxin556** [comment]
@zhangfudiyi ，你好，我遇到了你最开始说的，loss在3-8之间徘徊的情况，请问你是怎么解决的？

**Comment by zhangfudiyi** [comment]
我就是微调了他给的数据模型，也就是他说的finetune。你要知道怎么去复制他训练好的参数，他有给我们下载地址，你下载就好了，在model里面。 @dianxin556

**Comment by dianxin556** [comment]
要改他里面的哪些参数？我把里面的lr_mult和decay_mult都设置成1，就出现了上面你说的那种情况。 @zhangfudiyi

**Comment by zhangfudiyi** [comment]
你不会不知道怎么finetune吧！不要全部改，看你想微调那一层，你全改了那相当于你全部随机了参数，我只训练了最后全连接层，你先看看怎么finetune，你知道这个了，你肯定就知道怎么改了。我也不知道我说的对不对，个人理解而已。 @dianxin556

**Comment by dianxin556** [comment]
好的，谢谢！ @zhangfudiyi
