### ISSUE TITLE
请教一个浅显的问题

### ISSUE THREAD

**Issue by thu-zxs** [pinguo-luhaofang/tripletloss#19]
@pinguo-luhaofang 请问triplet loss训练好的模型是不是不能直接拿来做分类？而是测试的时候只能输入两个样本图片，比较他们输出feature之间的距离，用某个阈值判定他们是不是同一个人？
谢谢！

**Comment by pinguo-luhaofang** [comment]
tripletloss训练是为了拉大ap和an样本间的距离，测试是按照你说的方法来进行。
分类其实softmax已经非常强了。

**Comment by thu-zxs** [comment]
@pinguo-luhaofang 感谢解答
