### ISSUE TITLE
Hello，I  use your example_layers to train but got error

### ISSUE THREAD

**Issue by yzk0281** [pinguo-luhaofang/tripletloss#2]
norm2layer.py, line 32, in forward
X_normalized = preprocessing..
NameError: global name 'preprocessing'  is not  defined

**Comment by yzk0281** [comment]
OK
from sklearn import preprocessing
maybe solve this
I am wondering that  if  it is ok to  train a new vggface model via your example_layers ？
Can  I  fine  tune from the released VGG_FACE.caffemodel？
I tried it  but  error occurs， because  my  train data  has  only 529 identities， but the  released model  has  2622, what  should  I do  if  I  want to  fine-tune the released 2622 model from mine 529 data?

**Comment by pinguo-luhaofang** [comment]
You need to fix your layer's output. 
Rename your output layer then load the weights from VGG model.
