### ISSUE TITLE
遇到一个很奇怪的错误，请大家看一下

### ISSUE THREAD

**Issue by louielu1027** [pinguo-luhaofang/tripletloss#33]
I0817 04:13:15.119854  3010 layer_factory.hpp:74] Creating layer data
I0817 04:13:15.155990  3010 net.cpp:90] Creating Layer data
I0817 04:13:15.156023  3010 net.cpp:368] data -> data
I0817 04:13:15.156049  3010 net.cpp:368] data -> labels
I0817 04:13:15.156061  3010 net.cpp:120] Setting up data
100
I0817 04:13:15.164710  3010 net.cpp:127] Top shape: 30 3 224 224 (4515840)
I0817 04:13:15.164723  3010 net.cpp:127] Top shape: 30 (30)
I0817 04:13:15.164732  3010 layer_factory.hpp:74] Creating layer conv1_1
I0817 04:13:15.164748  3010 net.cpp:90] Creating Layer conv1_1
I0817 04:13:15.164757  3010 net.cpp:410] conv1_1 <- data
I0817 04:13:15.164768  3010 net.cpp:368] conv1_1 -> conv1_1
I0817 04:13:15.164782  3010 net.cpp:120] Setting up conv1_1
I0817 04:13:15.213511  3010 net.cpp:127] Top shape: 30 64 224 224 (96337920)
段错误 (核心已转储)

这个段错误是什么东西？

**Comment by ksnzh** [comment]
Segmentation fault
