### ISSUE TITLE
有关datalayer.py的可能的问题

### ISSUE THREAD

**Issue by thu-zxs** [pinguo-luhaofang/tripletloss#6]
你好！感谢你实现的tripletloss！现在发现一个可能的逻辑错误报告如下：
52行：`personname = self.data_container._sample_person.keys()[rand]`
rand应该是index吧？
以及前面：
`index = max(0,rand - 1)
 if index == 0 :
   index = 1`
当rand是1，那么index也是1，这样找到的就不是negative samples了

**Comment by pinguo-luhaofang** [comment]
感谢你抛出的问题，确实是这样的，我已经调整了对应的代码
